name: delete-old-links
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all the old links
        run: |
          curl --request POST \
          --url 'https://lnk.jacksonoppenheim.com/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
